changelog:
  exclude:
    labels:
      - ignore-for-release
      - documentation
    authors:
      - dependabot

  categories:
    - title: "Breaking changes"
      labels:
        - breaking-change

    - title: "New features"
      labels:
        - enhancement
        - feature

    - title: "Fixes"
      labels:
        - bug
        - fix

    - title: "Performance and stability"
      labels:
        - performance
        - stability

    - title: "Other changes"
      labels:
        - "*"
